# Generated by Django 5.2.8 on 2026-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='referral_goal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
