# Generated by Django 5.2.8 on 2026-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
