# Generated by Django 6.0.7 on 2026-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
