# Generated by Django 5.2.8 on 2026-07-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('fashion', 'Fashion'), ('food', 'Food & Restaurant'), ('health', 'Health'), ('education', 'Education'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('ecommerce', 'E-commerce'), ('travel', 'Travel & Tourism'), ('professional_services', 'Professional Services'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
